/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodieesoft.frames;

import com.foodieesoft.beans.Customer;

import com.foodieesoft.dao.CustomerDAO;
import com.foodieesoft.dao.UserDAO;
import com.foodieesoft.daoImpl.CustomerDAOImpl;
import com.foodieesoft.daoImpl.UserDAOImpl;
import static com.foodieesoft.frames.HomePage.user_id;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vksoni
 */
public class DeliveryInfoPage extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryInfoPage
     */
    DefaultTableModel tableModelCustomer;
    public ArrayList<Customer> customers_list;
    TableRowSorter<DefaultTableModel> rowSorter = null;
    public static String uname;
    public String requestFrom = "";

    public DeliveryInfoPage() {
        initComponents();
        tableModelCustomer = (DefaultTableModel) this.jTableCustomer.getModel();
        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelCustomer);
        this.jTableCustomer.setRowSorter(rowSorter);
        this.jButtonCustomerRegister.setVisible(false);

        showInTable("");

    }

    public DeliveryInfoPage(String username) {
        super("Delivery Information");
        initComponents();
        tableModelCustomer = (DefaultTableModel) this.jTableCustomer.getModel();
        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelCustomer);
        this.jTableCustomer.setRowSorter(rowSorter);
        requestFrom = "salepage";

        this.jButtonCustomerRegister.setEnabled(false);
        this.jButtonbak2TableRes.setVisible(false);

        uname = username;

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });

        showInTable("");

    }

    public DeliveryInfoPage(String username, String title) {
        super("Delivery Information");
        initComponents();
        tableModelCustomer = (DefaultTableModel) this.jTableCustomer.getModel();
        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelCustomer);
        requestFrom = "tableReservation";

        this.jTableCustomer.setRowSorter(rowSorter);
        this.jButtonRegister.setEnabled(false);
        this.jLabelTitle.setText(title);
        uname = username;
        this.jButtonback.setVisible(false);
        this.jButtonCustomerRegister.setVisible(true);

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });

        showInTable("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomer = new javax.swing.JTable();
        jTextFieldCustomerSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonback = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jButtonCustomerRegister = new javax.swing.JButton();
        jButtonbak2TableRes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setBackground(new java.awt.Color(0, 0, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("User Type ");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel6.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 610, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Search");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTableCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableCustomer.setForeground(new java.awt.Color(0, 0, 51));
        jTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Customer Name", "Contact #", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCustomer.setToolTipText("Products");
        jTableCustomer.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCustomer.setGridColor(new java.awt.Color(0, 0, 51));
        jTableCustomer.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableCustomer.setSelectionForeground(new java.awt.Color(0, 204, 0));
        jTableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCustomer);
        if (jTableCustomer.getColumnModel().getColumnCount() > 0) {
            jTableCustomer.getColumnModel().getColumn(0).setMinWidth(80);
            jTableCustomer.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableCustomer.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 670, 350));

        jTextFieldCustomerSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCustomerSearch.setText("Enter text to search...");
        jTextFieldCustomerSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextFieldCustomerSearch.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldCustomerSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCustomerSearchMouseClicked(evt);
            }
        });
        jTextFieldCustomerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerSearchActionPerformed(evt);
            }
        });
        jTextFieldCustomerSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCustomerSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCustomerSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCustomerSearchKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCustomerSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 17, 610, 20));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 690, 420));

        jButtonback.setBackground(new java.awt.Color(255, 255, 255));
        jButtonback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonback.setForeground(new java.awt.Color(255, 255, 255));
        jButtonback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Antu_edit-undo.svg.png"))); // NOI18N
        jButtonback.setText("Back");
        jButtonback.setContentAreaFilled(false);
        jButtonback.setFocusPainted(false);
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        jButtonRegister.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(0, 19, 74));
        jButtonRegister.setText("Register Customer");
        jButtonRegister.setFocusPainted(false);
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 170, 30));

        jLabelTitle.setBackground(new java.awt.Color(0, 19, 74));
        jLabelTitle.setFont(new java.awt.Font("SimSun-ExtB", 1, 54)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Delivery Details ");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jButtonCustomerRegister.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCustomerRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCustomerRegister.setForeground(new java.awt.Color(0, 19, 74));
        jButtonCustomerRegister.setText("Register Customer");
        jButtonCustomerRegister.setFocusPainted(false);
        jButtonCustomerRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCustomerRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 170, 30));

        jButtonbak2TableRes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonbak2TableRes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonbak2TableRes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonbak2TableRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Antu_edit-undo.svg.png"))); // NOI18N
        jButtonbak2TableRes.setText("Back");
        jButtonbak2TableRes.setContentAreaFilled(false);
        jButtonbak2TableRes.setFocusPainted(false);
        jButtonbak2TableRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbak2TableResActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonbak2TableRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/bg.png"))); // NOI18N
        jLabel7.setText("Delivery Information");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerMouseClicked
        int customer_id = Integer.parseInt("" + this.jTableCustomer.getValueAt(this.jTableCustomer.getSelectedRow(), 0));
        if (requestFrom.equalsIgnoreCase("tableReservation")) {
            new TablesRerservationPage(uname, customer_id).setVisible(true);
            this.dispose();
        } else {
            new SalePage(customer_id, uname).setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_jTableCustomerMouseClicked

    private void jTextFieldCustomerSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCustomerSearchMouseClicked
        if (this.jTextFieldCustomerSearch.getText().equalsIgnoreCase("Enter text to search...")) {
            this.jTextFieldCustomerSearch.setText("");
        }    }//GEN-LAST:event_jTextFieldCustomerSearchMouseClicked

    private void jTextFieldCustomerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerSearchActionPerformed

    private void jTextFieldCustomerSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCustomerSearchKeyPressed
        if (this.jTextFieldCustomerSearch.getText().equalsIgnoreCase("Enter text to search...")) {
            this.jTextFieldCustomerSearch.setText("");
        }


    }//GEN-LAST:event_jTextFieldCustomerSearchKeyPressed

    private void jTextFieldCustomerSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCustomerSearchKeyReleased
        // TODO add your handling code here:
        String searchData = this.jTextFieldCustomerSearch.getText();

        showInTable(searchData);

        if (this.jTableCustomer.getRowCount() == 0) {
            this.jButtonRegister.setEnabled(true);
            this.jButtonbak2TableRes.setEnabled(true);
        }

    }//GEN-LAST:event_jTextFieldCustomerSearchKeyReleased

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jTextFieldCustomerSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCustomerSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerSearchKeyTyped

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
        if (requestFrom.equalsIgnoreCase("tableReservation")) {
            new TablesRerservationPage(uname).setVisible(true);

        } else {
            new SalePage(uname).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        new CustomerPage(this.jTextFieldCustomerSearch.getText(), uname).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonCustomerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerRegisterActionPerformed
        // TODO add your handling code here:
        new CustomerPage(this.jTextFieldCustomerSearch.getText(), uname, "TableReservation").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCustomerRegisterActionPerformed

    private void jButtonbak2TableResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbak2TableResActionPerformed
        // TODO add your handling code here:

        this.dispose();
        UserDAO userDAO = new UserDAOImpl();
        new TablesRerservationPage(userDAO.retriveUsername(user_id)).setVisible(true);

    }//GEN-LAST:event_jButtonbak2TableResActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryInfoPage().setVisible(true);
            }
        });
    }

    public void showInTable(String txt) {
        tableModelCustomer.setRowCount(0);
        CustomerDAO customerDAO = new CustomerDAOImpl();
        customers_list = customerDAO.searchCustomers(txt);
        for (Customer customer : customers_list) {
            Vector V = new Vector();
            V.add(customer.getCustomer_id());
            V.add(customer.getCustomer_name());
            V.add(customer.getContact());
            V.add(customer.getAddress());
            tableModelCustomer.addRow(V);

        }

    }

    private int showWarningMessage() {
        String[] buttonLabels = new String[]{"Yes", "No"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;

        return JOptionPane.showOptionDialog(this,
                "Are you sure you wanna close it!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                icon,
                buttonLabels,
                defaultOption);
    }

    private void handleClosing() {
        {
            int answer = showWarningMessage();

            switch (answer) {
                case JOptionPane.YES_OPTION:
                    dispose();
                    break;

                case JOptionPane.NO_OPTION:
                    break;

            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCustomerRegister;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonbak2TableRes;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCustomer;
    private javax.swing.JTextField jTextFieldCustomerSearch;
    // End of variables declaration//GEN-END:variables
}
