/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodieesoft.frames;

import com.foodieesoft.beans.Permissions;
import com.foodieesoft.dao.PermissionsDAO;
import com.foodieesoft.dao.UserDAO;
import com.foodieesoft.dao.UserTypesDAO;
import com.foodieesoft.daoImpl.PermisionsDAOImpl;
import com.foodieesoft.daoImpl.UserDAOImpl;
import com.foodieesoft.daoImpl.UserTpesDAOImpl;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vksoni
 */
public class HomePage1 extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public static int user_id;
    public static int user_cat_id;

    public HomePage1(int user_id, int user_cat_id) {
        super("Dashboard");
        initComponents();
        
        Toolkit toolkit=Toolkit.getDefaultToolkit();
        int xsize=(int)toolkit.getScreenSize().getWidth();
        int ysize=(int)toolkit.getScreenSize().getHeight();
        this.pack();
//        this.setSize(xsize,ysize);
        
        System.out.println("x"+xsize+" y:"+ysize);
        
//        this.jPanelMenu.setSize((int)(xsize*0.9409663), (int)(ysize*0.683125));
//        this.jPanelBase.setSize((int)(xsize*0.9482869692), (int)(ysize*0.7091666666));

        
//        this.jPanelMenu.setSize((int)(20), (int)(40));
//        this.jPanelBase.setSize((int)(20), (int)(40));
//        
        
//        System.out.println("menu"+jPanelMenu.getSize()+" base:"+jPanelBase.getSize());
//        
        
        UserDAO userDAO = new UserDAOImpl();
        this.jLabelUsename.setText(userDAO.retriveUsername(user_id));
        this.user_id = user_id;
        UserTypesDAO userTypesDAO = new UserTpesDAOImpl();
        if (!(userTypesDAO.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {
            this.jButtonUser.setEnabled(false);
            this.jButtonCustomer.setEnabled(false);
            this.jButtonSaleHistory.setEnabled(false);
            this.jButtonInventroyManagement.setEnabled(false);
            this.jButtonOrder.setEnabled(false);
            this.jButtonReportsManagement.setEnabled(false);
        } else {

            this.jButtonUser.setEnabled(true);
            this.jButtonCustomer.setEnabled(true);
            this.jButtonSaleHistory.setEnabled(true);
            this.jButtonInventroyManagement.setEnabled(true);
            this.jButtonOrder.setEnabled(true);
            this.jButtonReportsManagement.setEnabled(true);
        }
        checkPermissions(user_cat_id);

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });
        
        

//
//        if (!(dbManager.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {
//            this.jButtonPermissions.setVisible(false);
//        }
    }

    public HomePage1() {
        initComponents();
//        checkPermissions(user_cat_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsename = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButtonOrder = new javax.swing.JButton();
        jButtonInventroyManagement = new javax.swing.JButton();
        jButtonCustomer = new javax.swing.JButton();
        jButtonSaleHistory = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButtonReportsManagement = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel6.setBackground(new java.awt.Color(0, 19, 74));
        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 54)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 19, 74));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DASHBOARD");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/psdFoodieeSoft.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/pro.png"))); // NOI18N

        jLabelUsename.setBackground(new java.awt.Color(0, 0, 51));
        jLabelUsename.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUsename.setForeground(new java.awt.Color(0, 19, 74));
        jLabelUsename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsename.setText("Username");

        jLabelLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(0, 19, 74));
        jLabelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/logoutmini.png"))); // NOI18N
        jLabelLogout.setText("LOGOUT");
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });

        jPanelMenu.setBackground(new java.awt.Color(0, 19, 74));
        jPanelMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 19, 74), 2, true));
        jPanelMenu.setForeground(new java.awt.Color(255, 255, 255));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/employee.png"))); // NOI18N
        jButton2.setText("Employee Management");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonOrder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/cart.png"))); // NOI18N
        jButtonOrder.setText("Sales DashBoard");
        jButtonOrder.setBorder(null);
        jButtonOrder.setContentAreaFilled(false);
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        jButtonInventroyManagement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonInventroyManagement.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInventroyManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/purchase-guy.png"))); // NOI18N
        jButtonInventroyManagement.setText("Inventory Management");
        jButtonInventroyManagement.setBorder(null);
        jButtonInventroyManagement.setContentAreaFilled(false);
        jButtonInventroyManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInventroyManagementActionPerformed(evt);
            }
        });

        jButtonCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCustomer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/customer.png"))); // NOI18N
        jButtonCustomer.setText("Customer Management");
        jButtonCustomer.setBorder(null);
        jButtonCustomer.setContentAreaFilled(false);
        jButtonCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCustomerMouseClicked(evt);
            }
        });
        jButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerActionPerformed(evt);
            }
        });

        jButtonSaleHistory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSaleHistory.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSaleHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/analytics-04.png"))); // NOI18N
        jButtonSaleHistory.setText("Sales History");
        jButtonSaleHistory.setBorder(null);
        jButtonSaleHistory.setContentAreaFilled(false);
        jButtonSaleHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaleHistoryActionPerformed(evt);
            }
        });

        jButtonUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonUser.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/users.png"))); // NOI18N
        jButtonUser.setText("Employee Management");
        jButtonUser.setBorder(null);
        jButtonUser.setContentAreaFilled(false);
        jButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 19, 74));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("User Management");

        jButtonReportsManagement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonReportsManagement.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReportsManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/client_report_dock_icon_by_ornorm-d5e0d34.png"))); // NOI18N
        jButtonReportsManagement.setText("Reports Management");
        jButtonReportsManagement.setBorder(null);
        jButtonReportsManagement.setContentAreaFilled(false);
        jButtonReportsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportsManagementActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/order-mgmt (1).png"))); // NOI18N
        jButton11.setText("Order Management");
        jButton11.setBorder(null);
        jButton11.setContentAreaFilled(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/reserve-tbl-icon.png"))); // NOI18N
        jButton12.setText("Table Reservation System");
        jButton12.setBorder(null);
        jButton12.setContentAreaFilled(false);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/exit.png"))); // NOI18N
        jButton13.setText("Exit");
        jButton13.setBorder(null);
        jButton13.setContentAreaFilled(false);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addComponent(jButtonReportsManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(424, 424, 424))
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addComponent(jButtonOrder)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonInventroyManagement)
                                .addGap(6, 6, 6))
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addComponent(jButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSaleHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(66, 66, 66))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jButtonInventroyManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaleHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReportsManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addGap(12, 12, 12))
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112))
                                    .addComponent(jLabelUsename, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(jLabelLogout))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelUsename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
        // TODO add your handling code here:
        Window[] win = java.awt.Window.getWindows();
        for (int i = 0; i < win.length; i++) {
            win[i].dispose();
        }

        this.dispose();
        new LoginPage().setVisible(true);

    }//GEN-LAST:event_jLabelLogoutMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        new TablesRerservationPage().setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        UserDAO userDAO = new UserDAOImpl();
        new OrderManagement(userDAO.retriveUsername(user_id)).setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButtonReportsManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportsManagementActionPerformed
        // TODO add your handling code here:
        new ReportManagements(user_id).setVisible(true);
    }//GEN-LAST:event_jButtonReportsManagementActionPerformed

    private void jButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserActionPerformed
        // TODO add your handling code here:
        new UserManagement(user_id).setVisible(true);
    }//GEN-LAST:event_jButtonUserActionPerformed

    private void jButtonSaleHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaleHistoryActionPerformed
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAOImpl();
        new OrderDetailPage(userDAO.retriveUsername(user_id)).setVisible(true);
    }//GEN-LAST:event_jButtonSaleHistoryActionPerformed

    private void jButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerActionPerformed
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAOImpl();

        new CustomerPage(userDAO.retriveUsername(user_id)).setVisible(true);
    }//GEN-LAST:event_jButtonCustomerActionPerformed

    private void jButtonCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCustomerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCustomerMouseClicked

    private void jButtonInventroyManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInventroyManagementActionPerformed
        // TODO add your handling code here:
        new InventoryManagement(user_id).setVisible(true);
    }//GEN-LAST:event_jButtonInventroyManagementActionPerformed

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAOImpl();
        new SalePage(userDAO.retriveUsername(user_id)).setVisible(true);
    }//GEN-LAST:event_jButtonOrderActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAOImpl();
        new EmployeePage(userDAO.retriveUsername(user_id)).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage1().setVisible(true);
            }
        });
    }

    public void checkPermissions(int user_cat_id) {
        ArrayList<Permissions> permissions_name_list;
        PermissionsDAO permissionsDAO = new PermisionsDAOImpl();

        permissions_name_list = permissionsDAO.getUserPermissionName(user_cat_id);

        for (Permissions permissions : permissions_name_list) {
            if ((permissions.getPermission_name().equalsIgnoreCase("View Reports Management"))) {
                this.jButtonReportsManagement.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Sale History"))) {
                this.jButtonSaleHistory.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View User Management"))) {
                this.jButtonUser.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Inventory Management"))) {
                this.jButtonInventroyManagement.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Sale Dashboard"))) {
                this.jButtonOrder.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Customer Management"))) {
                this.jButtonCustomer.setEnabled(true);
            }
        }

    }

    private int showWarningMessage() {
        String[] buttonLabels = new String[]{"Yes", "No"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;

        return JOptionPane.showOptionDialog(this,
                "Are you sure you wanna close it!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                icon,
                buttonLabels,
                defaultOption);
    }

    private void handleClosing() {
        {
            int answer = showWarningMessage();

            switch (answer) {
                case JOptionPane.YES_OPTION:
                    System.exit(0);
                    break;

                case JOptionPane.NO_OPTION:
                    break;

            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCustomer;
    private javax.swing.JButton jButtonInventroyManagement;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JButton jButtonReportsManagement;
    private javax.swing.JButton jButtonSaleHistory;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelUsename;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
