/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodieesoft.frames;

import com.foodieesoft.beans.Permissions;
import com.foodieesoft.dao.PermissionsDAO;
import com.foodieesoft.dao.UserDAO;
import com.foodieesoft.dao.UserTypesDAO;
import com.foodieesoft.daoImpl.PermisionsDAOImpl;
import com.foodieesoft.daoImpl.UserDAOImpl;
import com.foodieesoft.daoImpl.UserTpesDAOImpl;
import static com.foodieesoft.frames.UserManagement.user_cat_id;
import java.awt.Color;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vksoni
 */
public class InventoryManagement extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public static int user_id;
    public static int user_cat_id = LoginPage.user_cat_id;

    public InventoryManagement(int user_id) {
        super("Inventory Management");
        initComponents();
        UserDAO userDAO = new UserDAOImpl();
        this.jLabelUsename.setText(userDAO.retriveUsername(user_id));
        this.user_id = user_id;

        UserTypesDAO userTypesDAO = new UserTpesDAOImpl();
        if (!(userTypesDAO.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {
            this.jButtonProductStock.setEnabled(false);
            this.jButtonProductCat.setEnabled(false);
            this.jButtonProductRawMaterial.setEnabled(true);

        } else {

            this.jButtonProductStock.setEnabled(true);
            this.jButtonProductCat.setEnabled(true);
            this.jButtonProductRawMaterial.setEnabled(true);

        }
        checkPermissions(user_cat_id);

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });
    }

    public InventoryManagement() {
        initComponents();
//        checkPermissions(user_cat_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsename = new javax.swing.JLabel();
        jPanelHomePage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonProductStock = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonProductCat = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonProductRawMaterial = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonInventroyManagement = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 19, 74));
        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 54)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inventory Management");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 910, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/pro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        jLabelUsename.setBackground(new java.awt.Color(0, 0, 51));
        jLabelUsename.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUsename.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsename.setText("Username");
        getContentPane().add(jLabelUsename, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 200, -1));

        jPanelHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelHomePage.setMinimumSize(new java.awt.Dimension(750, 450));
        jPanelHomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 19, 74), 2, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonProductStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/product.png"))); // NOI18N
        jButtonProductStock.setBorder(null);
        jButtonProductStock.setContentAreaFilled(false);
        jButtonProductStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductStockActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonProductStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 190, 140));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 19, 74));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Products Stock");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jButtonProductCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/img_263507.png"))); // NOI18N
        jButtonProductCat.setBorder(null);
        jButtonProductCat.setContentAreaFilled(false);
        jButtonProductCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductCatActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonProductCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 160, 140));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 19, 74));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Food Categoies ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jButtonProductRawMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/inventory-management-software-500x500.png"))); // NOI18N
        jButtonProductRawMaterial.setBorder(null);
        jButtonProductRawMaterial.setContentAreaFilled(false);
        jButtonProductRawMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductRawMaterialActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonProductRawMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 170, 150));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 19, 74));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Raw Materials Management");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jPanelHomePage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 900, 280));

        getContentPane().add(jPanelHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 920, 320));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/logoutmini.png"))); // NOI18N
        jLabel2.setText("LOGOUT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Antu_edit-undo.svg.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jButtonInventroyManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/purchase-guy.png"))); // NOI18N
        jButtonInventroyManagement.setBorder(null);
        jButtonInventroyManagement.setContentAreaFilled(false);
        jButtonInventroyManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInventroyManagementActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInventroyManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 160, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/bg.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProductCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductCatActionPerformed
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAOImpl();

        new mytest(userDAO.retriveUsername(user_id)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonProductCatActionPerformed

    private void jButtonProductStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductStockActionPerformed
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAOImpl();

        new ProductPage(userDAO.retriveUsername(user_id)).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonProductStockActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        Window[] win = java.awt.Window.getWindows();
        for (int i = 0; i < win.length; i++) {
            win[i].dispose();
        }
        this.dispose();
        new LoginPage().setVisible(true);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButtonInventroyManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInventroyManagementActionPerformed
    }//GEN-LAST:event_jButtonInventroyManagementActionPerformed

    private void jButtonProductRawMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductRawMaterialActionPerformed
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAOImpl();

        new RawMaterialPage(userDAO.retriveUsername(user_id)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonProductRawMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryManagement().setVisible(true);
            }
        });
    }

    public void checkPermissions(int user_cat_id) {
        ArrayList<Permissions> permissions_name_list;
        PermissionsDAO permissionsDAO = new PermisionsDAOImpl();
        permissions_name_list = permissionsDAO.getUserPermissionName(user_cat_id);

        for (Permissions permissions : permissions_name_list) {
            if ((permissions.getPermission_name().equalsIgnoreCase("View Product Stock"))) {
                this.jButtonProductStock.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Product Categories"))) {
                this.jButtonProductCat.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Raw Material"))) {
                this.jButtonProductRawMaterial.setEnabled(true);
            }
        }

    }

    private int showWarningMessage() {
        String[] buttonLabels = new String[]{"Yes", "No"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;

        return JOptionPane.showOptionDialog(this,
                "Are you sure you wanna close it!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                icon,
                buttonLabels,
                defaultOption);
    }

    private void handleClosing() {
        {
            int answer = showWarningMessage();

            switch (answer) {
                case JOptionPane.YES_OPTION:
                    dispose();
                    break;

                case JOptionPane.NO_OPTION:
                    break;

            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonInventroyManagement;
    private javax.swing.JButton jButtonProductCat;
    private javax.swing.JButton jButtonProductRawMaterial;
    private javax.swing.JButton jButtonProductStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUsename;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHomePage;
    // End of variables declaration//GEN-END:variables
}
