/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodieesoft.frames;

import com.foodieesoft.beans.Order;
import com.foodieesoft.beans.OrderDetail;
import com.foodieesoft.dao.CustomerDAO;
import com.foodieesoft.dao.OrderDAO;
import com.foodieesoft.dao.UserDAO;
import com.foodieesoft.daoImpl.CustomerDAOImpl;
import com.foodieesoft.daoImpl.OrderDAOImpl;
import com.foodieesoft.daoImpl.UserDAOImpl;
import com.foodieesoft.dialog.SaleDetailsDialog;
import geeks.foodieesoft.util.CurrentDate;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vksoni
 */
public class OrderDetailPage extends javax.swing.JFrame {

    DefaultTableModel tableModelOrder;
    DefaultTableModel tableModelOrderDetail;
    TableRowSorter<DefaultTableModel> rowSorter = null;
    public static double total_sale;

    ArrayList<Order> order_list;
    ArrayList<Order> order_list_between_dates;

    ArrayList<OrderDetail> order_detail_list;
    String comingFromPage = "";

    public static int user_id = LoginPage.user_id;
    public static int user_cat_id = LoginPage.user_cat_id;

    public OrderDetailPage() {
        initComponents();
        tableModelOrder = (DefaultTableModel) this.jTableOrder.getModel();

        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelOrder);
        this.jTableOrder.setRowSorter(rowSorter);

        showInTable();
        this.jLabelTotalSale.setText("" + total_sale);

    }

    public OrderDetailPage(String username) {
        super("Order Details");
        initComponents();
        tableModelOrder = (DefaultTableModel) this.jTableOrder.getModel();

        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelOrder);
        this.jTableOrder.setRowSorter(rowSorter);
        this.jLabelProfileName.setText(username);
        showInTable();
        this.jLabelTotalSale.setText("" + total_sale);

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });

    }

    public OrderDetailPage(String username, String comingFrom) {
        super("Order Details");
        initComponents();
        tableModelOrder = (DefaultTableModel) this.jTableOrder.getModel();

        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelOrder);
        this.jTableOrder.setRowSorter(rowSorter);
        this.jLabelProfileName.setText(username);
        comingFromPage = comingFrom;
        this.jLabelTitle.setText("Over All Sell Report");
        showInTable();
        this.jLabelTotalSale.setText("" + total_sale);

        this.jButtonIcon.setIcon(new ImageIcon(Class.class.getResource("/geeks/foodieesoft/images/overallSmall.png")));

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jLabelTotalSale = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jTextFieldSerachProducts = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jDateChooseDate = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jButtonCustomerDateFilter = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonNewOrder = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelProfileName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonIcon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableOrder.setForeground(new java.awt.Color(0, 0, 51));
        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill Number", "Purchase Date", "Customer name", "Discount", "Total Bill (Rs)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOrder.setToolTipText("Products");
        jTableOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableOrder.setGridColor(new java.awt.Color(0, 0, 51));
        jTableOrder.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableOrder.setSelectionForeground(new java.awt.Color(0, 240, 0));
        jTableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOrderMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableOrder);
        if (jTableOrder.getColumnModel().getColumnCount() > 0) {
            jTableOrder.getColumnModel().getColumn(0).setMinWidth(90);
            jTableOrder.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTableOrder.getColumnModel().getColumn(0).setMaxWidth(90);
            jTableOrder.getColumnModel().getColumn(1).setMinWidth(120);
            jTableOrder.getColumnModel().getColumn(1).setMaxWidth(120);
            jTableOrder.getColumnModel().getColumn(3).setMinWidth(110);
            jTableOrder.getColumnModel().getColumn(3).setPreferredWidth(110);
            jTableOrder.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableOrder.getColumnModel().getColumn(4).setMinWidth(160);
            jTableOrder.getColumnModel().getColumn(4).setPreferredWidth(160);
            jTableOrder.getColumnModel().getColumn(4).setMaxWidth(160);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 900, 420));

        jLabelTotalSale.setBackground(new java.awt.Color(0, 19, 74));
        jLabelTotalSale.setFont(new java.awt.Font("OCR A Std", 1, 24)); // NOI18N
        jLabelTotalSale.setForeground(new java.awt.Color(102, 255, 0));
        jLabelTotalSale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalSale.setText("0.0");
        jLabelTotalSale.setOpaque(true);
        jPanel1.add(jLabelTotalSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 360, 40));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 240, -1));

        jTextFieldSerachProducts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSerachProducts.setText("search products ....");
        jTextFieldSerachProducts.setBorder(null);
        jTextFieldSerachProducts.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldSerachProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSerachProductsMouseClicked(evt);
            }
        });
        jTextFieldSerachProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSerachProductsActionPerformed(evt);
            }
        });
        jTextFieldSerachProducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSerachProductsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSerachProductsKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldSerachProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Total Sale:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Custom date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Click on the table row to watch Bill details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 240, -1));

        jLabel11.setBackground(new java.awt.Color(0, 19, 74));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sales History");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 900, 30));

        jRadioButton1.setBackground(new java.awt.Color(0, 19, 74));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Today's  Sales History");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, 30));

        jDateChooseDate.setDateFormatString("yyyy-MM-dd");
        jDateChooseDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooseDateMouseClicked(evt);
            }
        });
        jPanel1.add(jDateChooseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Search:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButtonCustomerDateFilter.setBackground(new java.awt.Color(0, 19, 74));
        jButtonCustomerDateFilter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCustomerDateFilter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCustomerDateFilter.setText("Filter");
        jButtonCustomerDateFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerDateFilterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCustomerDateFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 70, 20));

        jButton3.setBackground(new java.awt.Color(0, 19, 74));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/print_1.png"))); // NOI18N
        jButton3.setText("Print Records");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 40));

        jButtonNewOrder.setBackground(new java.awt.Color(0, 19, 74));
        jButtonNewOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNewOrder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/plus.png"))); // NOI18N
        jButtonNewOrder.setText("Place new Order");
        jButtonNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewOrderActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1190, 540));

        jLabelTitle.setBackground(new java.awt.Color(0, 19, 74));
        jLabelTitle.setFont(new java.awt.Font("SimSun-ExtB", 1, 54)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Sale History");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/logoutmini.png"))); // NOI18N
        jLabel3.setText("LOGOUT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, -1, -1));

        jLabelProfileName.setBackground(new java.awt.Color(0, 0, 51));
        jLabelProfileName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelProfileName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProfileName.setText("Username");
        getContentPane().add(jLabelProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/pro.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Antu_edit-undo.svg.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/analytics-04.png"))); // NOI18N
        jButtonIcon.setBorder(null);
        jButtonIcon.setContentAreaFilled(false);
        jButtonIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIconActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, 110));

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/bg.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrderMouseClicked
        // TODO add your handling code here:
        int order_id = (int) this.jTableOrder.getValueAt(this.jTableOrder.getSelectedRow(), 0);
        new SaleDetailsDialog(this, true, "" + this.jTableOrder.getValueAt(this.jTableOrder.getSelectedRow(), 1), order_id, "" + this.jTableOrder.getValueAt(this.jTableOrder.getSelectedRow(), 2)).setVisible(true);

    }//GEN-LAST:event_jTableOrderMouseClicked

    private void jTextFieldSerachProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsMouseClicked
        if (this.jTextFieldSerachProducts.getText().equalsIgnoreCase("search products ....")) {
            this.jTextFieldSerachProducts.setText("");
        }
    }//GEN-LAST:event_jTextFieldSerachProductsMouseClicked

    private void jTextFieldSerachProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSerachProductsActionPerformed

    private void jTextFieldSerachProductsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsKeyPressed
        if (this.jTextFieldSerachProducts.getText().equalsIgnoreCase("search products ....")) {
            this.jTextFieldSerachProducts.setText("");
        }
    }//GEN-LAST:event_jTextFieldSerachProductsKeyPressed

    private void jTextFieldSerachProductsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsKeyReleased
        // TODO add your handling code here:

        String searchData = this.jTextFieldSerachProducts.getText();
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchData));
    }//GEN-LAST:event_jTextFieldSerachProductsKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

        Window[] win = java.awt.Window.getWindows();
        for (int i = 0; i < win.length; i++) {
            win[i].dispose();
        }

        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (comingFromPage.equals("Reports page")) {
            try {
                new ReportManagements(user_id).setVisible(true);
            } catch (Exception e) {
            }

        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIconActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:

        if (this.jRadioButton1.isSelected()) {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + CurrentDate.getCurrentDate()));
            System.out.println(CurrentDate.getCurrentDate());
        } else {

            String searchData = this.jTextFieldSerachProducts.getText();
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchData));

        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jDateChooseDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooseDateMouseClicked


    }//GEN-LAST:event_jDateChooseDateMouseClicked

    private void jButtonCustomerDateFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerDateFilterActionPerformed

        SimpleDateFormat formats = new SimpleDateFormat("yyyy-MM-dd");
        try {
            String date = formats.format(this.jDateChooseDate.getDate());
            System.out.println(date);
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + date));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "select the dates first");

        }
    }//GEN-LAST:event_jButtonCustomerDateFilterActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        MessageFormat header = new MessageFormat("Foodiee Soft Overall Sale Report");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try {
            this.jTableOrder.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(OrderDetailPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewOrderActionPerformed
        UserDAO userDAO = new UserDAOImpl();
        new SalePage(userDAO.retriveUsername(user_id)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNewOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetailPage().setVisible(true);
            }
        });
    }

    public void showInTable() {

        try {
            tableModelOrder.setRowCount(0);
            OrderDAO orderDAO = new OrderDAOImpl();
            CustomerDAO customerDAO = new CustomerDAOImpl();
            order_list = orderDAO.getAllOrder();
            for (Order order : order_list) {
                Vector V = new Vector();
                V.add(order.getOrder_id());
                V.add(order.getCreated_date());
                V.add(customerDAO.getCustomerDetail(order.getCustomer_id()).getCustomer_name());
                V.add(orderDAO.getDiscountTypeById(order.getDiscount_id()).getDiscount_type() + ": " + order.getDiscount());
                V.add(order.getTotal_bill());
                total_sale += Double.parseDouble("" + order.getTotal_bill());
                tableModelOrder.addRow(V);
            }
        } catch (Exception e) {
        }
    }

    public void showInTableOrderBetweenDates(String from, String to) {
        tableModelOrder.setRowCount(0);
        OrderDAO orderDAO = new OrderDAOImpl();
        CustomerDAO customerDAO = new CustomerDAOImpl();
        order_list = orderDAO.getAllOrderBetweenDate(from, to);
        for (Order order : order_list) {
            Vector V = new Vector();
            V.add(order.getOrder_id());
            V.add(order.getCreated_date());
            V.add(customerDAO.getCustomerDetail(order.getCustomer_id()).getCustomer_name());
            V.add(orderDAO.getDiscountTypeById(order.getDiscount_id()).getDiscount_type() + ": " + order.getDiscount());
            V.add(order.getTotal_bill());
            total_sale += Double.parseDouble("" + order.getTotal_bill());
            tableModelOrder.addRow(V);
            this.jLabelTotalSale.setText("" + total_sale);
        }

    }

    private int showWarningMessage() {
        String[] buttonLabels = new String[]{"Yes", "No"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;

        return JOptionPane.showOptionDialog(this,
                "Are you sure you wanna close it!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                icon,
                buttonLabels,
                defaultOption);
    }

    private void handleClosing() {
        {
            int answer = showWarningMessage();

            switch (answer) {
                case JOptionPane.YES_OPTION:
                    dispose();
                    break;

                case JOptionPane.NO_OPTION:
                    break;

            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCustomerDateFilter;
    private javax.swing.JButton jButtonIcon;
    private javax.swing.JButton jButtonNewOrder;
    private com.toedter.calendar.JDateChooser jDateChooseDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelProfileName;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTotalSale;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTextField jTextFieldSerachProducts;
    // End of variables declaration//GEN-END:variables
}
