/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodieesoft.frames;

import com.foodieesoft.beans.Permissions;
import com.foodieesoft.beans.Product;
import com.foodieesoft.beans.RawMaterial;
import com.foodieesoft.dao.PermissionsDAO;
import com.foodieesoft.dao.RawProductsDAO;
import com.foodieesoft.dao.UserDAO;
import com.foodieesoft.dao.UserTypesDAO;
import com.foodieesoft.daoImpl.PermisionsDAOImpl;
import com.foodieesoft.daoImpl.RawProductsDAOImpl;
import com.foodieesoft.daoImpl.UserDAOImpl;
import com.foodieesoft.daoImpl.UserTpesDAOImpl;
import com.foodieesoft.dialog.JDialogRawMaterial;
import geeks.foodieesoft.util.CurrentDate;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Currency;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vksoni
 */
public class RawMaterialPage extends javax.swing.JFrame {

    /**
     * Creates new form UserType
     */
    DefaultTableModel tableModelProduct;
    public ArrayList<RawMaterial> raw_materials_list;
    TableRowSorter<DefaultTableModel> rowSorter = null;
    RawMaterial rawMaterial;
    public int user_id = LoginPage.user_id;
    public int user_cat_id = LoginPage.user_cat_id;

    public RawMaterialPage() {
        initComponents();
        tableModelProduct = (DefaultTableModel) this.jTableRawProduct.getModel();

        showInTable();
        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelProduct);
        this.jTableRawProduct.setRowSorter(rowSorter);

        UserTypesDAO userDAO = new UserTpesDAOImpl();

        if (!(userDAO.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {

            this.jButtonSave.setEnabled(false);
            checkPermissions(user_cat_id);
        } else {
            this.jButtonSave.setEnabled(true);

        }

    }

    public RawMaterialPage(String username) {
        super("Raw Materials Management");
        initComponents();
        tableModelProduct = (DefaultTableModel) this.jTableRawProduct.getModel();
        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelProduct);
        this.jTableRawProduct.setRowSorter(rowSorter);
        showInTable();
        this.jLabelProfileName.setText(username);

        this.jButtonSave.setEnabled(false);

        checkPermissions(user_cat_id);
        UserTypesDAO userDAO = new UserTpesDAOImpl();

        if (!(userDAO.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {

            this.jButtonSave.setEnabled(false);
            checkPermissions(user_cat_id);
        } else {
            this.jButtonSave.setEnabled(true);

        }

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {

                handleClosing();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRawProduct = new javax.swing.JTable();
        jTextFieldSerachProducts = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelProfileName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonProductStock = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSave.setBackground(new java.awt.Color(0, 19, 74));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/plus.png"))); // NOI18N
        jButtonSave.setText("Add");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        jTableRawProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableRawProduct.setForeground(new java.awt.Color(0, 0, 51));
        jTableRawProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Date", "Product Name", "Price", "QTY", "Created At"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRawProduct.setToolTipText("Products");
        jTableRawProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableRawProduct.setGridColor(new java.awt.Color(0, 0, 51));
        jTableRawProduct.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableRawProduct.setSelectionForeground(new java.awt.Color(0, 240, 0));
        jTableRawProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRawProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRawProduct);
        if (jTableRawProduct.getColumnModel().getColumnCount() > 0) {
            jTableRawProduct.getColumnModel().getColumn(0).setMinWidth(90);
            jTableRawProduct.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTableRawProduct.getColumnModel().getColumn(0).setMaxWidth(90);
            jTableRawProduct.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTableRawProduct.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTableRawProduct.getColumnModel().getColumn(4).setMinWidth(90);
            jTableRawProduct.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTableRawProduct.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1250, 380));

        jTextFieldSerachProducts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSerachProducts.setText("search products ....");
        jTextFieldSerachProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jTextFieldSerachProducts.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldSerachProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSerachProductsMouseClicked(evt);
            }
        });
        jTextFieldSerachProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSerachProductsActionPerformed(evt);
            }
        });
        jTextFieldSerachProducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSerachProductsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSerachProductsKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldSerachProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 300, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("SEARCH:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 80, -1));

        jButton3.setBackground(new java.awt.Color(0, 19, 74));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/print_1.png"))); // NOI18N
        jButton3.setText("Print Records");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1280, 450));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/pro.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/logoutmini.png"))); // NOI18N
        jLabel3.setText("LOGOUT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 120, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 19, 74));
        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 54)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Raw Materials");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1280, -1));

        jLabelProfileName.setBackground(new java.awt.Color(0, 0, 51));
        jLabelProfileName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelProfileName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProfileName.setText("Username");
        getContentPane().add(jLabelProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 90, 150, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Antu_edit-undo.svg.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/house-icon.png"))); // NOI18N
        jButton2.setText("Home");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jButtonProductStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/inventory-management-software-500x500.png"))); // NOI18N
        jButtonProductStock.setBorder(null);
        jButtonProductStock.setContentAreaFilled(false);
        jButtonProductStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductStockActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProductStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, 150));

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/bg.png"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        new JDialogRawMaterial(this, true, user_id).setVisible(true);
        showInTable();

        {
    }//GEN-LAST:event_jButtonSaveActionPerformed
    }
    private void jTableRawProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRawProductMouseClicked
        // TODO add your handling code here:
        int product_id = Integer.parseInt("" + this.jTableRawProduct.getValueAt(this.jTableRawProduct.getSelectedRow(), 0));
        RawProductsDAO rawMaterialDAO = new RawProductsDAOImpl();

        rawMaterial = rawMaterialDAO.getRawProduct(product_id);

        new JDialogRawMaterial(this, true, user_id, rawMaterial).setVisible(true);
        showInTable();

    }//GEN-LAST:event_jTableRawProductMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

        Window[] win = java.awt.Window.getWindows();
        for (int i = 0; i < win.length; i++) {
            win[i].dispose();
        }

        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        new InventoryManagement(user_id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldSerachProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsMouseClicked
        if (this.jTextFieldSerachProducts.getText().equalsIgnoreCase("search products ....")) {
            this.jTextFieldSerachProducts.setText("");
        }
    }//GEN-LAST:event_jTextFieldSerachProductsMouseClicked

    private void jTextFieldSerachProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSerachProductsActionPerformed

    private void jTextFieldSerachProductsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsKeyPressed
        if (this.jTextFieldSerachProducts.getText().equalsIgnoreCase("search products ....")) {
            this.jTextFieldSerachProducts.setText("");
        }
    }//GEN-LAST:event_jTextFieldSerachProductsKeyPressed

    private void jTextFieldSerachProductsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsKeyReleased
        // TODO add your handling code here:

        String searchData = this.jTextFieldSerachProducts.getText();
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchData));
    }//GEN-LAST:event_jTextFieldSerachProductsKeyReleased

    private void jButtonProductStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductStockActionPerformed
    }//GEN-LAST:event_jButtonProductStockActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        MessageFormat header = new MessageFormat("Foodiee Soft Raw Materials");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            this.jTableRawProduct.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(RawMaterialPage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RawMaterialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RawMaterialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RawMaterialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RawMaterialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RawMaterialPage().setVisible(true);
            }
        });
    }

    public void showInTable() {
        tableModelProduct.setRowCount(0);
        RawProductsDAO rawMaterialDAO = new RawProductsDAOImpl();

        raw_materials_list = rawMaterialDAO.getAllRawProducts();
        for (RawMaterial rawMaterials : raw_materials_list) {
            Vector V = new Vector();
            V.add(rawMaterials.getRaw_materials_id());
            V.add(rawMaterials.getCreated_date());
            V.add(rawMaterials.getRaw_product_name());
            V.add(rawMaterials.getPrice());
            V.add(rawMaterials.getQuantity());
            V.add(rawMaterials.getCreated_date());

            tableModelProduct.addRow(V);
        }
    }

    public void checkPermissions(int user_cat_id) {
        ArrayList<Permissions> permissions_name_list;
        PermissionsDAO permissionsDAO = new PermisionsDAOImpl();
        permissions_name_list = permissionsDAO.getUserPermissionName(user_cat_id);

        for (Permissions permissions : permissions_name_list) {
            if ((permissions.getPermission_name().equalsIgnoreCase("Add Raw Material"))) {
                this.jButtonSave.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("Update Raw Material"))) {

            } else if ((permissions.getPermission_name().equalsIgnoreCase("Delete Raw Material"))) {

            }

        }
    }
    private int showWarningMessage() {
        String[] buttonLabels = new String[]{"Yes", "No"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;

        return JOptionPane.showOptionDialog(this,
                "Are you sure you wanna close it!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                icon,
                buttonLabels,
                defaultOption);
    }

    private void handleClosing() {
        {
            int answer = showWarningMessage();

            switch (answer) {
                case JOptionPane.YES_OPTION:
                    dispose();
                    break;

                case JOptionPane.NO_OPTION:
                    break;

            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonProductStock;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelProfileName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRawProduct;
    private javax.swing.JTextField jTextFieldSerachProducts;
    // End of variables declaration//GEN-END:variables
}
