/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodieesoft.frames;

import com.foodieesoft.beans.Permissions;
import com.foodieesoft.dao.PermissionsDAO;
import com.foodieesoft.dao.UserDAO;
import com.foodieesoft.dao.UserTypesDAO;
import com.foodieesoft.daoImpl.PermisionsDAOImpl;
import com.foodieesoft.daoImpl.UserDAOImpl;
import com.foodieesoft.daoImpl.UserTpesDAOImpl;
import com.foodieesoft.dialog.NewJDialogReport;
import static com.foodieesoft.frames.HomePage.user_id;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.eclipse.birt.core.framework.Platform;
import org.eclipse.birt.report.engine.api.EngineConfig;
import org.eclipse.birt.report.engine.api.HTMLRenderOption;
import org.eclipse.birt.report.engine.api.IReportEngine;
import org.eclipse.birt.report.engine.api.IReportEngineFactory;
import org.eclipse.birt.report.engine.api.IReportRunnable;
import org.eclipse.birt.report.engine.api.IRunAndRenderTask;

/**
 *
 * @author Vksoni
 */
public class ReportManagements extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public static int user_id;
    public static int user_cat_id = LoginPage.user_cat_id;

    public ReportManagements(int user_id) {
        super("Report Management");
        initComponents();
        UserDAO userDAO = new UserDAOImpl();
        this.jLabelUsename.setText(userDAO.retriveUsername(user_id));
        this.jLabelLoading.setVisible(false);
        this.jLabelLoading1.setVisible(false);
        this.user_id = user_id;
        this.jButtonBack.setVisible(true);
        this.jButtonBack2SaleDetail.setVisible(false);
        UserTypesDAO userTypesDAO = new UserTpesDAOImpl();
        if (!(userTypesDAO.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {
            this.jButtonCustomReport.setEnabled(false);
            this.jButtonTodaysSaleReport.setEnabled(false);
            this.jButtonuMonthlyReport.setEnabled(false);

        } else {

            this.jButtonCustomReport.setEnabled(true);
            this.jButtonTodaysSaleReport.setEnabled(true);
            this.jButtonuMonthlyReport.setEnabled(true);

        }
        checkPermissions(user_cat_id);
        
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                
                handleClosing();
            }
        });
    }

    public ReportManagements(int user_id, String order) {
        super("Report Mangement");
        initComponents();
        UserDAO userDAO = new UserDAOImpl();
        this.jLabelUsename.setText(userDAO.retriveUsername(user_id));
        this.jLabelLoading.setVisible(false);
        this.jLabelLoading1.setVisible(false);
        this.user_id = user_id;
        this.jButtonBack.setVisible(false);
        this.jButtonBack2SaleDetail.setVisible(true);
        UserTypesDAO userTypesDAO = new UserTpesDAOImpl();

        if (!(userTypesDAO.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {
            this.jButtonCustomReport.setEnabled(false);
            this.jButtonTodaysSaleReport.setEnabled(false);
            this.jButtonuMonthlyReport.setEnabled(false);

        } else {

            this.jButtonCustomReport.setEnabled(true);
            this.jButtonTodaysSaleReport.setEnabled(true);
            this.jButtonuMonthlyReport.setEnabled(true);

        }
        checkPermissions(user_cat_id);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                
                handleClosing();
            }
        });
    }

    public ReportManagements() {
        initComponents();
        this.jLabelLoading1.setVisible(false);

//        checkPermissions(user_cat_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsename = new javax.swing.JLabel();
        jPanelHomePage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonTodaysSaleReport = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonuMonthlyReport = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonCustomReport = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabelLoading1 = new javax.swing.JLabel();
        jLabelLoading = new javax.swing.JLabel();
        jButtonuMonthlyReport1 = new javax.swing.JButton();
        jButtonCustomReport1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonBack2SaleDetail = new javax.swing.JButton();
        jButtonReportsManagement = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 19, 74));
        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 54)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Repots Management");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/pro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, -1));

        jLabelUsename.setBackground(new java.awt.Color(0, 0, 51));
        jLabelUsename.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUsename.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsename.setText("Username");
        getContentPane().add(jLabelUsename, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 170, -1));

        jPanelHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelHomePage.setMinimumSize(new java.awt.Dimension(750, 450));
        jPanelHomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 19, 74), 2, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTodaysSaleReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/report.png"))); // NOI18N
        jButtonTodaysSaleReport.setBorder(null);
        jButtonTodaysSaleReport.setContentAreaFilled(false);
        jButtonTodaysSaleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodaysSaleReportActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTodaysSaleReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 140));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 19, 74));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Today's Sale Report ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jButtonuMonthlyReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/monthly.png"))); // NOI18N
        jButtonuMonthlyReport.setBorder(null);
        jButtonuMonthlyReport.setContentAreaFilled(false);
        jButtonuMonthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonuMonthlyReportActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonuMonthlyReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 160, 140));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 19, 74));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Monthly Sale Report");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jButtonCustomReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/cccc.png"))); // NOI18N
        jButtonCustomReport.setBorder(null);
        jButtonCustomReport.setContentAreaFilled(false);
        jButtonCustomReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomReportActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCustomReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 150, 160));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 19, 74));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Overall Sales Report");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, -1, -1));

        jLabelLoading1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/loading (1).gif"))); // NOI18N
        jLabelLoading1.setText("jLabel3");
        jPanel1.add(jLabelLoading1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 250, 250));

        jLabelLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/loading (1).gif"))); // NOI18N
        jLabelLoading.setText("jLabel3");
        jPanel1.add(jLabelLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 250));

        jButtonuMonthlyReport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/monthly.png"))); // NOI18N
        jButtonuMonthlyReport1.setBorder(null);
        jButtonuMonthlyReport1.setContentAreaFilled(false);
        jButtonuMonthlyReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonuMonthlyReport1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonuMonthlyReport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 160, 140));

        jButtonCustomReport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/overall.png"))); // NOI18N
        jButtonCustomReport1.setBorder(null);
        jButtonCustomReport1.setContentAreaFilled(false);
        jButtonCustomReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomReport1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCustomReport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 190, 160));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 19, 74));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Custom Report");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jPanelHomePage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 300));

        getContentPane().add(jPanelHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 920, 320));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/logoutmini.png"))); // NOI18N
        jLabel2.setText("LOGOUT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, -1, -1));

        jButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Antu_edit-undo.svg.png"))); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.setFocusPainted(false);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jButtonBack2SaleDetail.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBack2SaleDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBack2SaleDetail.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack2SaleDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Antu_edit-undo.svg.png"))); // NOI18N
        jButtonBack2SaleDetail.setText("BACK");
        jButtonBack2SaleDetail.setContentAreaFilled(false);
        jButtonBack2SaleDetail.setFocusPainted(false);
        jButtonBack2SaleDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack2SaleDetailActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack2SaleDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jButtonReportsManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/client_report_dock_icon_by_ornorm-d5e0d34.png"))); // NOI18N
        jButtonReportsManagement.setBorder(null);
        jButtonReportsManagement.setContentAreaFilled(false);
        jButtonReportsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportsManagementActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReportsManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 160, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/bg.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCustomReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomReportActionPerformed
        // TODO add your handling code here:
        new NewJDialogReport(this, true).setVisible(true);

    }//GEN-LAST:event_jButtonCustomReportActionPerformed

    private void jButtonuMonthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonuMonthlyReportActionPerformed
        // TODO add your handling code here:
//        this.jButtonuMonthlyReport.setVisible(false);
//        this.jLabelLoading1.setVisible(true);
//        this.jButtonuMonthlyReport.setVisible(true);
//        this.jLabelLoading1.setVisible(false);
        UserDAO userDAO = new UserDAOImpl();

        new MonthlySalesReport(userDAO.retriveUsername(user_id)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonuMonthlyReportActionPerformed

    private void jButtonTodaysSaleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodaysSaleReportActionPerformed
        // TODO add your handling code here:
        this.jButtonTodaysSaleReport.setVisible(false);
        this.jLabelLoading.setVisible(true);
//        genDailyReport();
        UserDAO userDAO = new UserDAOImpl();

        new todaysSaleReport(userDAO.retriveUsername(user_id)).setVisible(true);
        this.dispose();
        this.jButtonTodaysSaleReport.setVisible(true);
        this.jLabelLoading.setVisible(false);


    }//GEN-LAST:event_jButtonTodaysSaleReportActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
     
         Window[] win=java.awt.Window.getWindows();
        for (int i = 0; i < win.length; i++) {
            win[i].dispose();
        }
        
        this.dispose();
        new LoginPage().setVisible(true);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButtonBack2SaleDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack2SaleDetailActionPerformed
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAOImpl();
        new OrderDetailPage(userDAO.retriveUsername(user_id)).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonBack2SaleDetailActionPerformed

    private void jButtonReportsManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportsManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportsManagementActionPerformed

    private void jButtonuMonthlyReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonuMonthlyReport1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonuMonthlyReport1ActionPerformed

    private void jButtonCustomReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomReport1ActionPerformed
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAOImpl();

        new OrderDetailPage(userDAO.retriveUsername(user_id), "Reports page").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCustomReport1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportManagements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportManagements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportManagements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportManagements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportManagements().setVisible(true);
            }
        });
    }

//    public void checkPermissions(int user_cat_id) {
//        ArrayList<Permissions> permissions_name_list;
//        permissions_name_list = dbManager.getUserPermissionName(user_cat_id);
//
//        for (Permissions permissions : permissions_name_list) {
//            if ((permissions.getPermission_name().equalsIgnoreCase("View User"))) {
//                this.jButtonUser.setEnabled(true);
//            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Customer"))) {
//                this.jButtonCustomer.setEnabled(true);
//            } else if ((permissions.getPermission_name().equalsIgnoreCase("View User Type"))) {
//                this.jButtonUserType.setEnabled(true);
//            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Food Category"))) {
//                this.jButtonCatagorey.setEnabled(true);
//            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Question"))) {
//                this.jButtonQuestion.setEnabled(true);
//            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Order"))) {
//                this.jButtonOrder.setEnabled(true);
//            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Product"))) {
//                this.jButtonProduct.setEnabled(true);
//            }
//        }
//
//    }
    public void genDailyReport() {

        new Thread(new Runnable() {

            int i = 1;

            @Override
            public void run() {
                while (true) {
                    i += 10;
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }).start();

        IReportEngine engine = null;
        EngineConfig config = null;
        String report_name = "Report of today sale ";

        File f = new File("Reports\\DailyReport/" + report_name + ".pdf");
        if (f.exists()) {
            f.delete();
        }
        try {

            config = new EngineConfig();
            //config.setLogConfig("c:/temp/test", Level.FINEST);
            Platform.startup(config);
            IReportEngineFactory factory = (IReportEngineFactory) Platform
                    .createFactoryObject(IReportEngineFactory.EXTENSION_REPORT_ENGINE_FACTORY);
            engine = factory.createReportEngine(config);

            IReportRunnable design = null;
            //Open the report design
            String rpath = "reprotFiles/today_sale.rptdesign";

            design = engine.openReportDesign(rpath);

            IRunAndRenderTask task = engine.createRunAndRenderTask(design);
//           task.setParameterValue("custo_id", ""+6);
//            task.validateParameters();
//            // int order=DbManager.getMaxOrder();
            HTMLRenderOption options = new HTMLRenderOption();
            options.setOutputFileName("Reports\\DailyReport/" + report_name + ".pdf");
            options.setOutputFormat("pdf");

            //options.setHtmlRtLFlag(false);
            //options.setEmbeddable(false);
            //options.setImageDirectory("C:\\test\\images");
            //PDFRenderOption options = new PDFRenderOption();
            //options.setOutputFileName("c:/temp/test.pdf");
            //options.setOutputFormat("pdf");
            task.setRenderOption(options);
            task.run();
            task.close();
            engine.destroy();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        } finally {
            Platform.shutdown();
            System.out.println("reportGenerated");
            JOptionPane.showMessageDialog(rootPane, "report scucessfully generated");

            try {

                if ((new File("Reports\\DailyReport/" + report_name + ".pdf")).exists()) {

                    Process p = Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler Reports\\DailyReport/" + report_name + ".pdf");
                    p.waitFor();

                } else {

                    System.out.println("File is not exists");

                }

                System.out.println("Done");

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }

    public void checkPermissions(int user_cat_id) {
        ArrayList<Permissions> permissions_name_list;
        PermissionsDAO permissionsDAO = new PermisionsDAOImpl();
        permissions_name_list = permissionsDAO.getUserPermissionName(user_cat_id);

        for (Permissions permissions : permissions_name_list) {
            if ((permissions.getPermission_name().equalsIgnoreCase("Generate Today's Sale Report"))) {
                this.jButtonTodaysSaleReport.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("Generate Monthly Sale Report"))) {
                this.jButtonuMonthlyReport.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View User Type"))) {
                this.jButtonCustomReport.setEnabled(true);
            }
        }

    }
    
    private int showWarningMessage() {
        String[] buttonLabels = new String[] {"Yes", "No"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;
         
        return JOptionPane.showOptionDialog(this,
                "Are you sure you wanna close it!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                icon,
                buttonLabels,
                defaultOption);    
    }

      private void handleClosing() {
         {
            int answer = showWarningMessage();
             
            switch (answer) {
                case JOptionPane.YES_OPTION:
                    dispose();
                    break;
                     
                case JOptionPane.NO_OPTION:
                    break;
                     
             
            }
        }     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBack2SaleDetail;
    private javax.swing.JButton jButtonCustomReport;
    private javax.swing.JButton jButtonCustomReport1;
    private javax.swing.JButton jButtonReportsManagement;
    private javax.swing.JButton jButtonTodaysSaleReport;
    private javax.swing.JButton jButtonuMonthlyReport;
    private javax.swing.JButton jButtonuMonthlyReport1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLoading;
    private javax.swing.JLabel jLabelLoading1;
    private javax.swing.JLabel jLabelUsename;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHomePage;
    // End of variables declaration//GEN-END:variables
}
