/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodieesoft.frames;

import com.foodieesoft.beans.Customer;
import com.foodieesoft.beans.FoodCategory;
import com.foodieesoft.beans.Permissions;
import com.foodieesoft.beans.Questions;
import com.foodieesoft.beans.User;
import com.foodieesoft.beans.UserType;
import com.foodieesoft.dao.PermissionsDAO;
import com.foodieesoft.dao.QuestionsDAO;
import com.foodieesoft.dao.UserDAO;
import com.foodieesoft.dao.UserTypesDAO;
import com.foodieesoft.daoImpl.PermisionsDAOImpl;
import com.foodieesoft.daoImpl.QuestionsDAOImpl;
import com.foodieesoft.daoImpl.UserDAOImpl;
import com.foodieesoft.daoImpl.UserTpesDAOImpl;
import com.foodieesoft.dialog.JDialogFoodCat;
import com.foodieesoft.dialog.JDialogUser;
import geeks.foodieesoft.util.CurrentDate;
import geeks.foodieesoft.util.InputValidation;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Vksoni
 */
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form UserType
     */
    DefaultTableModel tableModelCustomer;
    DefaultComboBoxModel comboBoxModelUserType;
    DefaultComboBoxModel comboBoxModelQuestions;
    public ArrayList<UserType> user_types_list;
    public ArrayList<Questions> questions_list;
    public ArrayList<User> users_list;

    public int user_id = LoginPage.user_id;
    public int user_cat_id = LoginPage.user_cat_id;

    public UserPage() {
        initComponents();
        tableModelCustomer = (DefaultTableModel) this.jTableUser.getModel();
        

        showInTable();
        UserTypesDAO userTypesDAO = new UserTpesDAOImpl();
        if (!(userTypesDAO.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {

            this.jButtonSave.setEnabled(false);
            checkPermissions(user_cat_id);
        } else {
            this.jButtonSave.setEnabled(true);

        }

    }

    public UserPage(String username) {
        super("User Accounts");
        initComponents();
        
        
        tableModelCustomer = (DefaultTableModel) this.jTableUser.getModel();

        showInTable();
        this.jLabelProfileName.setText(username);

        UserTypesDAO userTypesDAO = new UserTpesDAOImpl();
        if (!(userTypesDAO.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {

            this.jButtonSave.setEnabled(false);
            checkPermissions(user_cat_id);
        } else {
            this.jButtonSave.setEnabled(true);

        }
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                
                handleClosing();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelProfileName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonUserAccounts = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSave.setBackground(new java.awt.Color(0, 19, 74));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/plus.png"))); // NOI18N
        jButtonSave.setText("Add");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 40));

        jTableUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableUser.setForeground(new java.awt.Color(0, 0, 51));
        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Type", "Username", "Name", "Contact#", "Address", "Question", "Answer", "Created At"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUser.setToolTipText("Products");
        jTableUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableUser.setGridColor(new java.awt.Color(0, 0, 51));
        jTableUser.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableUser.setSelectionForeground(new java.awt.Color(0, 204, 0));
        jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUser);
        if (jTableUser.getColumnModel().getColumnCount() > 0) {
            jTableUser.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableUser.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTableUser.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTableUser.getColumnModel().getColumn(3).setPreferredWidth(15);
            jTableUser.getColumnModel().getColumn(4).setPreferredWidth(10);
            jTableUser.getColumnModel().getColumn(6).setMinWidth(120);
            jTableUser.getColumnModel().getColumn(6).setPreferredWidth(120);
            jTableUser.getColumnModel().getColumn(6).setMaxWidth(120);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1200, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1220, 490));

        jLabel14.setBackground(new java.awt.Color(0, 19, 74));
        jLabel14.setFont(new java.awt.Font("SimSun-ExtB", 1, 54)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("User Accounts");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1220, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/pro.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, -1));

        jLabelProfileName.setBackground(new java.awt.Color(0, 0, 51));
        jLabelProfileName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelProfileName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProfileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProfileName.setText("Username");
        getContentPane().add(jLabelProfileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 70, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/logoutmini.png"))); // NOI18N
        jLabel3.setText("LOGOUT");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Antu_edit-undo.svg.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/house-icon.png"))); // NOI18N
        jButton2.setText("Home");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jButtonUserAccounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/acount.png"))); // NOI18N
        jButtonUserAccounts.setBorder(null);
        jButtonUserAccounts.setContentAreaFilled(false);
        jButtonUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserAccountsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUserAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, 140));

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/bg.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 140));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
          new JDialogUser(this, true,user_id).setVisible(true);
          showInTable();

        {    
    }//GEN-LAST:event_jButtonSaveActionPerformed
    }
    private void jTableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserMouseClicked
        // TODO add your handling code here:
     
        
        User user=new User();
        user=users_list.get(this.jTableUser.getSelectedRow());
          new JDialogUser(this, true,user_id,user,this.jTableUser.getSelectedRow()).setVisible(true);
          showInTable();

//        int user_type_id = users_list.get(this.jTableUser.getSelectedRow()).getUser_cat_id();
//        int question_id = users_list.get(this.jTableUser.getSelectedRow()).getQuestion_id();
//
//        this.jTextFieldUsername.setText(users_list.get(this.jTableUser.getSelectedRow()).getUser_name());
//        this.jTextFieldPassword.setText(users_list.get(this.jTableUser.getSelectedRow()).getPassword());
//        this.jTextFieldRetypePassword.setText("");
//        this.jTextFieldContact.setText(users_list.get(this.jTableUser.getSelectedRow()).getContact_num());
//        this.jTextFieldAnswer.setText(users_list.get(this.jTableUser.getSelectedRow()).getAnswer());
//        this.jTextFieldAddress.setText(users_list.get(this.jTableUser.getSelectedRow()).getAddress());
//        this.jTextFieldName.setText(users_list.get(this.jTableUser.getSelectedRow()).getName());
//
//        QuestionsDAO questionsDAO = new QuestionsDAOImpl();
//        UserTypesDAO userTypesDAO = new UserTpesDAOImpl();
//
//        this.jComboBoxUserType.setSelectedItem(userTypesDAO.getUserType(user_type_id));
//        this.jComboBoxQuestions.setSelectedItem(questionsDAO.getQuestion(question_id));



    }//GEN-LAST:event_jTableUserMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
       
         Window[] win=java.awt.Window.getWindows();
        for (int i = 0; i < win.length; i++) {
            win[i].dispose();
        }
        
        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        new UserManagement(user_id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        System.out.println(user_cat_id);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonUserAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserAccountsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserAccountsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }


    public void showInTable() {
        tableModelCustomer.setRowCount(0);
        UserDAO userDAO = new UserDAOImpl();
        UserTypesDAO userTypesDAO = new UserTpesDAOImpl();
        QuestionsDAO questionsDAO = new QuestionsDAOImpl();

        users_list = userDAO.getAllUsers();
        for (User user : users_list) {
            Vector V = new Vector();
            V.add(userTypesDAO.getUserType(user.getUser_cat_id()));
            V.add(user.getUser_name());
            V.add(user.getName());
            V.add(user.getContact_num());
            V.add(user.getAddress());
            V.add(questionsDAO.getQuestion(user.getQuestion_id()));
            V.add(user.getAnswer());
            V.add(user.getCreated_date());

            tableModelCustomer.addRow(V);
        }
    }

    public void checkPermissions(int user_cat_id) {
        ArrayList<Permissions> permissions_name_list;
        PermissionsDAO permissionsDAO = new PermisionsDAOImpl();
        permissions_name_list = permissionsDAO.getUserPermissionName(user_cat_id);

        for (Permissions permissions : permissions_name_list) {
            if ((permissions.getPermission_name().equalsIgnoreCase("Add User"))) {
                this.jButtonSave.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("Update User"))) {

            } else if ((permissions.getPermission_name().equalsIgnoreCase("Delete User"))) {

            }

        }
    }
    
    private int showWarningMessage() {
        String[] buttonLabels = new String[] {"Yes", "No"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;
         
        return JOptionPane.showOptionDialog(this,
                "Are you sure you wanna close it!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE,
                icon,
                buttonLabels,
                defaultOption);    
    }

      private void handleClosing() {
         {
            int answer = showWarningMessage();
             
            switch (answer) {
                case JOptionPane.YES_OPTION:
                    dispose();
                    break;
                     
                case JOptionPane.NO_OPTION:
                    break;
                     
             
            }
        }     
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUserAccounts;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelProfileName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUser;
    // End of variables declaration//GEN-END:variables
}
