/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodieesoft.dialog;

import com.foodieesoft.beans.Customer;
import com.foodieesoft.dao.QuestionsDAO;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.foodieesoft.beans.Questions;
import com.foodieesoft.dao.CustomerDAO;
import com.foodieesoft.daoImpl.CustomerDAOImpl;

import org.eclipse.birt.core.framework.Platform;
import org.eclipse.birt.report.engine.api.EngineConfig;
import org.eclipse.birt.report.engine.api.HTMLRenderOption;
import org.eclipse.birt.report.engine.api.IReportEngine;
import org.eclipse.birt.report.engine.api.IReportEngineFactory;
import org.eclipse.birt.report.engine.api.IReportRunnable;
import org.eclipse.birt.report.engine.api.IRunAndRenderTask;
import com.foodieesoft.daoImpl.QuestionsDAOImpl;
import com.foodieesoft.daoImpl.UserTpesDAOImpl;
import com.foodieesoft.frames.SalePage;
import com.foodieesoft.frames.TablesRerservationPage;
import geeks.foodieesoft.util.CurrentDate;
import geeks.foodieesoft.util.InputValidation;

/**
 *
 * @author Vksoni
 */
public class JDialogCustomer extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialogReport
     */
    private int userId;
    private Customer customer;
    CustomerDAO customerDAO;
    String username;
    boolean goSalePage=false,goTableRes=false;
    
    

    public JDialogCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDialogCustomer(java.awt.Frame parent, boolean modal, int userId,String username,boolean goSalePage,boolean  goTableRes) {
        super(parent, modal);
        this.userId = userId;
        this.username=username;
        this.goSalePage=goSalePage;
        this.goTableRes=goTableRes;
        initComponents();

        this.jButtonUpdate.setVisible(false);
        this.jButtonDelete.setVisible(false);
                customerDAO = new CustomerDAOImpl();


    }

    public JDialogCustomer(java.awt.Frame parent, boolean modal, int userId, Customer customer) {
        super(parent, modal);
        this.userId = userId;
        this.customer = customer;
        initComponents();
        
        this.jTextFieldCustomerName.setText(customer.getCustomer_name());
        this.jTextFieldContact.setText(customer.getContact());
        this.jTextFieldAddress.setText(customer.getAddress());
        this.jLabelTitle.setText(customer.getCustomer_name());
        customerDAO = new CustomerDAOImpl();

        this.jButtonSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCustomerName = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldContact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonSave1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setBackground(new java.awt.Color(0, 19, 74));
        jLabelTitle.setFont(new java.awt.Font("SimSun-ExtB", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Add Customer");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/bg.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 19, 74), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSave.setBackground(new java.awt.Color(0, 19, 74));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/save.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 150, 40));

        jButtonUpdate.setBackground(new java.awt.Color(0, 19, 74));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/update.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 40));

        jButtonDelete.setBackground(new java.awt.Color(0, 19, 74));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/delete.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 150, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 450, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 450, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 450, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("CONTACT*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 280, -1));

        jTextFieldCustomerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCustomerName.setText("Enter Customer Name..");
        jTextFieldCustomerName.setBorder(null);
        jTextFieldCustomerName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldCustomerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCustomerNameMouseClicked(evt);
            }
        });
        jTextFieldCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerNameActionPerformed(evt);
            }
        });
        jTextFieldCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCustomerNameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 450, -1));

        jTextFieldAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAddress.setText("Enter Address...");
        jTextFieldAddress.setBorder(null);
        jTextFieldAddress.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldAddressMouseClicked(evt);
            }
        });
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });
        jTextFieldAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAddressKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 450, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("ADDRESS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 20));

        jTextFieldContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldContact.setText("Enter Contact Number..");
        jTextFieldContact.setBorder(null);
        jTextFieldContact.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldContactMouseClicked(evt);
            }
        });
        jTextFieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactActionPerformed(evt);
            }
        });
        jTextFieldContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldContactKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 450, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("CUSTOMER NAME*");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 340, -1));

        jButtonSave1.setBackground(new java.awt.Color(0, 19, 74));
        jButtonSave1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave1.setText("Cancel");
        jButtonSave1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSave1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 510, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        String contact = this.jTextFieldContact.getText();
        String address = this.jTextFieldAddress.getText();
        String customer_name = this.jTextFieldCustomerName.getText();

// get a matcher object
        if (!(customer_name.equalsIgnoreCase("Enter Customer Name..") || customer_name.equalsIgnoreCase("")
                || contact.equalsIgnoreCase("Enter Contact Number..") || contact.equalsIgnoreCase("")
                || address.equalsIgnoreCase("Enter Address..."))) {

            if (!InputValidation.validateName(customer_name)) {
                JOptionPane.showMessageDialog(this, "Invalid Customer name Format!");

            } else if (!InputValidation.validatePhoneNum(contact)) {
                JOptionPane.showMessageDialog(this, "Invalid phone number Format!");
            } else {
                int custId = customerDAO.saveCustomer(new Customer(0, 1, contact, address,
                        userId, 0, CurrentDate.getCurrentDate(), "", customer_name));

                if (custId != 0) {
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Successfully added");
                    if(goSalePage==true){
                     new SalePage(custId, "").setVisible(true);
                    }
                    else if(goTableRes==true){
                      new TablesRerservationPage(username, custId).setVisible(true);
                    }

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill required field");

        }


    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:

        int dialogButton = JOptionPane.showConfirmDialog(null, "Are you sure?", "Save Update", JOptionPane.YES_NO_OPTION);

        if (dialogButton == JOptionPane.YES_OPTION) {

            int customer_id = customer.getCustomer_id();
            String contact = this.jTextFieldContact.getText();
            String address = this.jTextFieldAddress.getText();
            String customer_name = this.jTextFieldCustomerName.getText();

            if (!(customer_name.equalsIgnoreCase("Enter Customer Name..") || customer_name.equalsIgnoreCase("")
                    || contact.equalsIgnoreCase("Enter Contact Number..") || contact.equalsIgnoreCase("")
                    || address.equalsIgnoreCase("Enter Address..."))) {

                if (!InputValidation.validateName(customer_name)) {
                    JOptionPane.showMessageDialog(this, "Invalid Customer name Format!");

                } else if (!InputValidation.validatePhoneNum(contact)) {
                    JOptionPane.showMessageDialog(this, "Invalid phone number Format!");
                } else {
                    int i = customerDAO.modifyCustomers(new Customer(customer_id, 0, contact, address, 0, userId, "", CurrentDate.getCurrentDate(), customer_name));

                    if (i != 0) {
                        this.dispose();
                        JOptionPane.showMessageDialog(this, "Updated Sucessfully");

                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please fill required field");
            }

        } else {
        }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed

        int dialogButton = JOptionPane.showConfirmDialog(null, "Are you sure?", "Save Update", JOptionPane.YES_NO_OPTION);

        if (dialogButton == JOptionPane.YES_OPTION) {

        int customer_id = customer.getCustomer_id();
        int i = customerDAO.removeCustomer(new Customer(customer_id, 0, "", "", 0, 0, "", "", ""));

        if (i != 0) {
            this.dispose();
            JOptionPane.showMessageDialog(this, "Deleted Sucessfully");

}

        } else {
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldCustomerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCustomerNameMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldCustomerName.getText().equalsIgnoreCase("Enter Customer Name..")) {
            this.jTextFieldCustomerName.setText("");
        }
    }//GEN-LAST:event_jTextFieldCustomerNameMouseClicked

    private void jTextFieldCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerNameActionPerformed

    private void jTextFieldCustomerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCustomerNameKeyPressed
        if (this.jTextFieldCustomerName.getText().equalsIgnoreCase("Enter Customer Name..")) {
            this.jTextFieldCustomerName.setText("");
        }
    }//GEN-LAST:event_jTextFieldCustomerNameKeyPressed

    private void jTextFieldAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAddressMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldAddress.getText().equalsIgnoreCase("Enter Address...")) {
            this.jTextFieldAddress.setText("");
        }
    }//GEN-LAST:event_jTextFieldAddressMouseClicked

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddressKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldAddress.getText().equalsIgnoreCase("Enter Address...")) {
            this.jTextFieldAddress.setText("");
        }
    }//GEN-LAST:event_jTextFieldAddressKeyPressed

    private void jTextFieldContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldContactMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldContact.getText().equalsIgnoreCase("Enter Contact Number..")) {
            this.jTextFieldContact.setText("");
        }
    }//GEN-LAST:event_jTextFieldContactMouseClicked

    private void jTextFieldContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactActionPerformed

    private void jTextFieldContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldContactKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldContact.getText().equalsIgnoreCase("Enter Contact Number..")) {
            this.jTextFieldContact.setText("");
        }
    }//GEN-LAST:event_jTextFieldContactKeyPressed

    private void jButtonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSave1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSave1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCustomer dialog = new JDialogCustomer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void genReport(String from, String to) {

        new Thread(new Runnable() {

            int i = 1;

            @Override
            public void run() {
                while (true) {
                    i += 10;
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                    }

                }
            }
        }).start();

        IReportEngine engine = null;
        EngineConfig config = null;
        Map parameters = new HashMap();
        parameters.put("from", "" + from);
        parameters.put("to", to);
        String reportTitle = "custom report of " + to + " to " + from;
        String path = "Reports\\CustomReports/" + reportTitle + ".pdf";
        File f = new File(path);
        if (f.exists()) {
            f.delete();
        }
        try {

            config = new EngineConfig();
            //config.setLogConfig("c:/temp/test", Level.FINEST);
            Platform.startup(config);
            IReportEngineFactory factory = (IReportEngineFactory) Platform
                    .createFactoryObject(IReportEngineFactory.EXTENSION_REPORT_ENGINE_FACTORY);
            engine = factory.createReportEngine(config);

            IReportRunnable design = null;
            //Open the report design
            String rpath = "reprotFiles/custom_report.rptdesign";

            design = engine.openReportDesign(rpath);

            IRunAndRenderTask task = engine.createRunAndRenderTask(design);
//           task.setParameterValue("custo_id", ""+6);
//            task.validateParameters();
//            // int order=DbManager.getMaxOrder();
            HTMLRenderOption options = new HTMLRenderOption();
            options.setOutputFileName(path);
            options.setOutputFormat("pdf");

            task.setRenderOption(options);

            task.setParameterValues(parameters);

            //options.setHtmlRtLFlag(false);
            //options.setEmbeddable(false);
            //options.setImageDirectory("C:\\test\\images");
            //PDFRenderOption options = new PDFRenderOption();
            //options.setOutputFileName("c:/temp/test.pdf");
            //options.setOutputFormat("pdf");
            task.setRenderOption(options);
            task.run();
            task.close();
            engine.destroy();
        } catch (Exception ex) {
            System.out.println("report generated");
            System.out.println(ex.getMessage());
        } finally {
            Platform.shutdown();
            JOptionPane.showMessageDialog(rootPane, "report scucessfully generated");

            try {

                if ((new File("Reports\\CustomReports/" + reportTitle + ".pdf")).exists()) {

                    Process p = Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler Reports\\CustomReports/" + reportTitle + ".pdf");
                    p.waitFor();

                } else {

                    System.out.println("File is not exists");

                }

                System.out.println("Done");

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSave1;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldCustomerName;
    // End of variables declaration//GEN-END:variables
}
