/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodieesoft.dialog;

import com.foodieesoft.beans.Employee;
import com.foodieesoft.dao.QuestionsDAO;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.foodieesoft.beans.Questions;
import com.foodieesoft.dao.EmployeeDAO;
import com.foodieesoft.daoImpl.EmployeeDAOImpl;

import org.eclipse.birt.core.framework.Platform;
import org.eclipse.birt.report.engine.api.EngineConfig;
import org.eclipse.birt.report.engine.api.HTMLRenderOption;
import org.eclipse.birt.report.engine.api.IReportEngine;
import org.eclipse.birt.report.engine.api.IReportEngineFactory;
import org.eclipse.birt.report.engine.api.IReportRunnable;
import org.eclipse.birt.report.engine.api.IRunAndRenderTask;
import com.foodieesoft.daoImpl.QuestionsDAOImpl;
import com.foodieesoft.daoImpl.UserTpesDAOImpl;
import com.foodieesoft.frames.EmployeePage;
import geeks.foodieesoft.util.CurrentDate;
import geeks.foodieesoft.util.InputValidation;
import java.text.ParseException;

/**
 *
 * @author Vksoni
 */
public class JDialogEmployee extends javax.swing.JDialog {
    /**
     * Creates new form NewJDialogReport
     */
     private int userId;
     private Employee  employee;

    public JDialogEmployee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
 public JDialogEmployee(java.awt.Frame parent, boolean modal,int userId) {
        super(parent, modal);
        this.userId=userId;
        initComponents();
        
        this.jButtonUpdate.setVisible(false);
        this.jButtonDelete.setVisible(false);
    }

  public JDialogEmployee(java.awt.Frame parent, boolean modal,int userId,Employee employee) {
        super(parent, modal);
        this.userId=userId;
        this.employee=employee;
        initComponents();
       this.jLabelTitle.setText(employee.getEmployee_name());
  this.jTextFieldEmployeeName.setText(employee.getEmployee_name());
        this.jTextFieldContact.setText(employee.getContact_num());
        this.jTextFieldSalary.setText("" + employee.getSalary());
        this.jTextFieldDesgination.setText("" + employee.getDesignation());

        String dateValue = employee.getCreation_date();
        try {
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
            this.jDateChooseHireDate.setDate(date);

        } catch (ParseException ex) {
            Logger.getLogger(EmployeePage.class.getName()).log(Level.SEVERE, null, ex);
        }        this.jButtonSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldEmployeeName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextFieldDesgination = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTextFieldContact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jTextFieldSalary = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jDateChooseHireDate = new com.toedter.calendar.JDateChooser();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setBackground(new java.awt.Color(0, 19, 74));
        jLabelTitle.setFont(new java.awt.Font("SimSun-ExtB", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Add Employee");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 510, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/bg.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 19, 74), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSave.setBackground(new java.awt.Color(0, 19, 74));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/save.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 150, 40));

        jButtonUpdate.setBackground(new java.awt.Color(0, 19, 74));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/update.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 150, 40));

        jButtonDelete.setBackground(new java.awt.Color(0, 19, 74));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/delete.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 150, 40));

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("EMPLOYEE NAME*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 470, -1));

        jTextFieldEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEmployeeName.setText("Enter Employee Name...");
        jTextFieldEmployeeName.setBorder(null);
        jTextFieldEmployeeName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldEmployeeName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldEmployeeNameMouseClicked(evt);
            }
        });
        jTextFieldEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmployeeNameActionPerformed(evt);
            }
        });
        jTextFieldEmployeeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmployeeNameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 470, 20));

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("DESGINATION*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 330, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 470, -1));

        jTextFieldDesgination.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldDesgination.setText("Enter Desgination...");
        jTextFieldDesgination.setBorder(null);
        jTextFieldDesgination.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldDesgination.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDesginationMouseClicked(evt);
            }
        });
        jTextFieldDesgination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDesginationActionPerformed(evt);
            }
        });
        jTextFieldDesgination.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDesginationKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldDesgination, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 470, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 470, -1));

        jTextFieldContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldContact.setText("Enter Contact...");
        jTextFieldContact.setBorder(null);
        jTextFieldContact.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldContactMouseClicked(evt);
            }
        });
        jTextFieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactActionPerformed(evt);
            }
        });
        jTextFieldContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldContactKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 470, 20));

        jLabel10.setBackground(new java.awt.Color(0, 0, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("CONTACT*");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 300, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 470, -1));

        jTextFieldSalary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSalary.setText("Enter Salary...");
        jTextFieldSalary.setBorder(null);
        jTextFieldSalary.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSalaryMouseClicked(evt);
            }
        });
        jTextFieldSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaryActionPerformed(evt);
            }
        });
        jTextFieldSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSalaryKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 470, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 51));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("SALARY*");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 280, -1));

        jDateChooseHireDate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooseHireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 470, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 470, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 51));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("HIRE DATE*");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 310, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 510, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed

int dialogButton = JOptionPane.showConfirmDialog (null, "Are you sure?","WARNING",JOptionPane.YES_NO_OPTION);

if(dialogButton == JOptionPane.YES_OPTION) {

EmployeeDAO employeeDAO =new EmployeeDAOImpl();
        int i = employeeDAO.removeEmployee(new Employee(employee.getEmployee_id(), "", "", 0.0, "", 0, 0, "", 0));

        if (i != 0) {
            this.dispose();
            JOptionPane.showMessageDialog(this, "Deleted Sucessfully");
        }

}else {}

        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:

        
        
int dialogButton = JOptionPane.showConfirmDialog (null, "Are you sure?","Save Update",JOptionPane.YES_NO_OPTION);

if(dialogButton == JOptionPane.YES_OPTION) {
        String ename = this.jTextFieldEmployeeName.getText();
        String contact = this.jTextFieldContact.getText();
        String desgination = this.jTextFieldDesgination.getText();
        double salary = 0.0;
        String hireDate = "";
                EmployeeDAO employeeDAO =new EmployeeDAOImpl();


        SimpleDateFormat formats = new SimpleDateFormat("yyyy-MM-dd");

        if (!(ename.equalsIgnoreCase("") || ename.equalsIgnoreCase("Enter Employee Name...")
                || contact.equalsIgnoreCase("") || contact.equalsIgnoreCase("Enter Contact...")
                || desgination.equalsIgnoreCase("") || desgination.equalsIgnoreCase("Enter Desgination..."))) {
            if (!InputValidation.validateName(ename)) {
                JOptionPane.showMessageDialog(this, "Invalid employee name Format!");

            } else if (!InputValidation.validateName(desgination)) {
                JOptionPane.showMessageDialog(this, "Invalid desgination Format!");
            } else if (!InputValidation.validatePhoneNum(contact)) {
                JOptionPane.showMessageDialog(this, "Invalid phone number Format!");
            }
            else if (!InputValidation.validateAmount(this.jTextFieldSalary.getText())) {
                JOptionPane.showMessageDialog(this, "Invalid salary Format!");
            }
            
            else {

            try {
                hireDate = formats.format(this.jDateChooseHireDate.getDate());

                try {
                    salary = Double.parseDouble("" + this.jTextFieldSalary.getText());

                    int status = employeeDAO.modifyEmployee(new Employee(employee.getEmployee_id(), ename, contact, salary, desgination, 0, userId, hireDate, 1));

                    if (status != 0) {
                        this.dispose();
                        JOptionPane.showMessageDialog(this, "Successfully updated");

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please select hire date ");

            }

        } }else {
            JOptionPane.showMessageDialog(this, "Please fill required field");
        }
}else {}

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
       String ename = this.jTextFieldEmployeeName.getText();
        String contact = this.jTextFieldContact.getText();
        String desgination = this.jTextFieldDesgination.getText();
        double salary = 0.0;
        String hireDate = "";
        EmployeeDAO employeeDAO =new EmployeeDAOImpl();

        SimpleDateFormat formats = new SimpleDateFormat("yyyy-MM-dd");

        if (!(ename.equalsIgnoreCase("") || ename.equalsIgnoreCase("Enter Employee Name...")
                || contact.equalsIgnoreCase("") || contact.equalsIgnoreCase("Enter Contact...")
                || desgination.equalsIgnoreCase("") || desgination.equalsIgnoreCase("Enter Desgination..."))) {

            if (!InputValidation.validateName(ename)) {
                JOptionPane.showMessageDialog(this, "Invalid employee name Format!");

            } else if (!InputValidation.validateName(desgination)) {
                JOptionPane.showMessageDialog(this, "Invalid desgination Format!");
            } else if (!InputValidation.validatePhoneNum(contact)) {
                JOptionPane.showMessageDialog(this, "Invalid phone number Format!");
            }
            else if (!InputValidation.validateAmount(this.jTextFieldSalary.getText())) {
                JOptionPane.showMessageDialog(this, "Invalid salary Format!");
            }
            
            else {

                try {
                    hireDate = formats.format(this.jDateChooseHireDate.getDate());

                    try {
                        salary = Double.parseDouble("" + this.jTextFieldSalary.getText());

                        int status = employeeDAO.saveEmployee(new Employee(0, ename, contact, salary, desgination, userId, 0, hireDate, 1));
                        if (status != 0) {
                            this.dispose();
                            JOptionPane.showMessageDialog(this, "Successfully added");
                            this.jTextFieldEmployeeName.setText("Enter Employee Name...");
                            this.jTextFieldDesgination.setText("Enter Desgination...");
                            this.jTextFieldSalary.setText("Enter Salary...");
                            this.jTextFieldContact.setText("Enter Contact...");

                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());

                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Please select hire date ");

                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill required field");
    }  
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldEmployeeNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmployeeNameMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldEmployeeName.getText().equalsIgnoreCase("Enter Employee Name...")) {
            this.jTextFieldEmployeeName.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmployeeNameMouseClicked

    private void jTextFieldEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmployeeNameActionPerformed

    private void jTextFieldEmployeeNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmployeeNameKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldEmployeeName.getText().equalsIgnoreCase("Enter Employee Name...")) {
            this.jTextFieldEmployeeName.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmployeeNameKeyPressed

    private void jTextFieldDesginationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDesginationMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldDesgination.getText().equalsIgnoreCase("Enter Desgination...")) {
            this.jTextFieldDesgination.setText("");
        }
    }//GEN-LAST:event_jTextFieldDesginationMouseClicked

    private void jTextFieldDesginationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDesginationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDesginationActionPerformed

    private void jTextFieldDesginationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDesginationKeyPressed
        // TODO add your handling code here:

        if (this.jTextFieldDesgination.getText().equalsIgnoreCase("Enter Desgination...")) {
            this.jTextFieldDesgination.setText("");
        }
    }//GEN-LAST:event_jTextFieldDesginationKeyPressed

    private void jTextFieldContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldContactMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldContact.getText().equalsIgnoreCase("Enter Contact...")) {
            this.jTextFieldContact.setText("");
        }
    }//GEN-LAST:event_jTextFieldContactMouseClicked

    private void jTextFieldContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactActionPerformed

    private void jTextFieldContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldContactKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldContact.getText().equalsIgnoreCase("Enter Contact...")) {
            this.jTextFieldContact.setText("");
        }
    }//GEN-LAST:event_jTextFieldContactKeyPressed

    private void jTextFieldSalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSalaryMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldSalary.getText().equalsIgnoreCase("Enter Salary...")) {
            this.jTextFieldSalary.setText("");
        }
    }//GEN-LAST:event_jTextFieldSalaryMouseClicked

    private void jTextFieldSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaryActionPerformed

    private void jTextFieldSalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSalaryKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldSalary.getText().equalsIgnoreCase("Enter Salary...")) {
            this.jTextFieldSalary.setText("");
        }

    }//GEN-LAST:event_jTextFieldSalaryKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEmployee dialog = new JDialogEmployee(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void genReport(String from ,String to) {

        new Thread(new Runnable() {

            int i = 1;

            @Override
            public void run() {
                while (true) {
                    i += 10;
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                    }

                }
            }
        }).start();

        IReportEngine engine = null;
        EngineConfig config = null;
        Map parameters = new HashMap();
        parameters.put("from", "" + from);
        parameters.put("to", to);
        String reportTitle = "custom report of "+to+" to "+from;
        String path = "Reports\\CustomReports/" + reportTitle + ".pdf";
        File f = new File(path);
        if (f.exists()) {
            f.delete();
        }
        try {

            config = new EngineConfig();
            //config.setLogConfig("c:/temp/test", Level.FINEST);
            Platform.startup(config);
            IReportEngineFactory factory = (IReportEngineFactory) Platform
                    .createFactoryObject(IReportEngineFactory.EXTENSION_REPORT_ENGINE_FACTORY);
            engine = factory.createReportEngine(config);

            IReportRunnable design = null;
            //Open the report design
            String rpath = "reprotFiles/custom_report.rptdesign";

            design = engine.openReportDesign(rpath);

            IRunAndRenderTask task = engine.createRunAndRenderTask(design);
//           task.setParameterValue("custo_id", ""+6);
//            task.validateParameters();
//            // int order=DbManager.getMaxOrder();
            HTMLRenderOption options = new HTMLRenderOption();
            options.setOutputFileName(path);
            options.setOutputFormat("pdf");

            task.setRenderOption(options);

            task.setParameterValues(parameters);

            //options.setHtmlRtLFlag(false);
            //options.setEmbeddable(false);
            //options.setImageDirectory("C:\\test\\images");
            //PDFRenderOption options = new PDFRenderOption();
            //options.setOutputFileName("c:/temp/test.pdf");
            //options.setOutputFormat("pdf");
            task.setRenderOption(options);
            task.run();
            task.close();
            engine.destroy();
        } catch (Exception ex) {
            System.out.println("report generated");
            System.out.println(ex.getMessage());
        } finally {
            Platform.shutdown();
            JOptionPane.showMessageDialog(rootPane, "report scucessfully generated");

            try {

                if ((new File("Reports\\CustomReports/" + reportTitle + ".pdf")).exists()) {

                    Process p = Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler Reports\\CustomReports/" + reportTitle + ".pdf");
                    p.waitFor();

                } else {

                    System.out.println("File is not exists");

                }

                System.out.println("Done");

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private com.toedter.calendar.JDateChooser jDateChooseHireDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldDesgination;
    private javax.swing.JTextField jTextFieldEmployeeName;
    private javax.swing.JTextField jTextFieldSalary;
    // End of variables declaration//GEN-END:variables
}
